version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bank-db-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_final:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: bank-backend-container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/bank_db

  # NEW SERVICE: The Frontend
  frontend:
    build: ./frontend
    container_name: bank-frontend-container
    ports:
      - "80:80"  # Maps port 80 (Standard Web) to the container

volumes:
  postgres_data_final: